[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyturk"
version = "0.1.0"
description = "A mini PyTorch-like deep learning framework built on scalar autograd, for clarity and gradient intuition."
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Nabin Oli" }]
license = { text = "MIT" }
keywords = ["deep learning", "autograd", "transformers", "micrograd", "MLP", "educational AI"]

dependencies = []

[project.optional-dependencies]
datasets = ["scikit-learn", "numpy"]
viz = ["graphviz", "matplotlib"]
dev = ["pytest", "scikit-learn", "numpy", "graphviz", "matplotlib"]

[project.urls]
Homepage = "https://github.com/nabin2004/pyturk"
Issues = "https://github.com/nabin2004/pyturk/issues"
